petyosi/react-virtuoso

src/Virtuoso.tsx, src/VirtuosoView.tsx
=> feat: add support for className prop

src/GroupedVirtuoso.tsx, src/Virtuoso.tsx, src/VirtuosoStore.tsx
I delete old PR cause i had my own mistake.This code work like a charm
If you want i can make PR to rep with docs
=> heightObserver feature

playground/README.md, playground/fakeData.ts, playground/grouped-load-on-demand.tsx, src/GroupedVirtuoso.tsx
Attempting to fix --> https://github.com/petyosi/react-virtuoso/issues/78
=> feat(groupedVirtuoso): expose rangeChanged

playground/grouped-load-on-demand.tsx, src/GroupedVirtuoso.tsx
For now we need to use the `rangedChanged` callback but this is better to check if we're at the bottom of the list :)
=> feat(groupedvirtuoso): support at bottom state changed

src/Virtuoso.tsx, src/VirtuosoList.tsx
=> Fix type for computeItemKey

package.json, src/GroupedVirtuoso.tsx, src/Virtuoso.tsx, src/VirtuosoList.tsx, src/VirtuosoStore.tsx, src/VirtuosoView.tsx, src/engines/scrollSeekEngine.ts, src/tinyrx.ts, tsconfig.json, yarn.lock
One of the issues found with the problem is described in #97.
Probably many other reincarnations exist. 
The root cause of the issue was that prop updates (in this case, the `renderItem` prop) 
had higher priority compared to the observable updates. 
The solution was to move the render function calculation inside the store.
=> Fix duplicate and inconsistent rendering sequence

src/engines/scrolledToBottomEngine.ts
=> Fix atBottom computation when content is smaller than the viewport.

playground/grid.tsx, playground/grouped-load-on-demand.tsx, playground/index.tsx, playground/issue-145.tsx, playground/timeline/bottom.tsx, playground/timeline/scroll-to-index.tsx, src/GroupedVirtuoso.tsx, src/Virtuoso.tsx, src/VirtuosoFiller.tsx, src/VirtuosoGrid.tsx, src/VirtuosoList.tsx, src/VirtuosoScroller.tsx, src/VirtuosoStore.tsx, src/VirtuosoView.tsx, test/Virtuoso.test.tsx
migrate react import 
from 
```
import React from 'react'
```
to
```
import * as React from 'react'
```
Closes #155
=> Migrate react import

README.md
Add [Stream](https://getstream.io/) as sponsor.
=> Add Stream as sponsor to README.

site/docs/getting-started.md
=> Spelling Update

src/scrollSeekSystem.ts
Fixes https://github.com/petyosi/react-virtuoso/issues/288
=> fix(): isSeeking detection when fast scrolling stops

src/List.tsx, src/components.tsx, src/hooks/useChangedChildSizes.ts, src/listSystem.ts, src/sizeSystem.ts
=> Add List.itemSize prop.

package.json
=> fix: remove unused react-app-polyfill dependency

src/Grid.tsx, src/List.tsx, src/components.tsx, src/interfaces.ts
[Related discussion](https://github.com/petyosi/react-virtuoso/discussions/412).
=> feat(): add item.data to computeItemKey of List

e2e/header-footer.tsx, src/sizeRangeSystem.ts
Fixes #406 #409
I have played with sizeRangeSystem after `yarn browse-examples` and following solution should work as expected. 
@petyosi  What do you think?
Also I still have some problems with this module - sometimes scroll flickering occurs for list with expandable cards. Hard to reproduce but could you please point me which systems might cause such issue so I could play with them? #418
=> fix: size range system for list with header

src/components.tsx
Use proper types in grid interface
=> fix(): grid types

examples/scroll-element-grid-scroller.tsx, examples/scroll-element-list-scroller.tsx
Updated scrollElement -> customScrollParent to match new prop name.
=> Fix scroll element examples

e2e/initial-topmost-item.test.ts, examples/initial-topmost-item.tsx, site/docs/initial-index.md, src/components.tsx, src/initialTopMostItemIndexSystem.ts, src/listStateSystem.ts
Modify the parameter of `initialTopMostItemIndex` to keep the same as `scrollToIndex`
=> feat(): add location parameter to initialTopMostItemIndex(#465)

site/docs/scroll-handling.md
=> docs(): scrollingStateChange -> isScrolling

src/List.tsx, src/Table.tsx, src/components.tsx, src/stateFlagsSystem.ts
Add atTopThreshold, similar to atBottomThreshold
maybe help： [issue#641](https://github.com/petyosi/react-virtuoso/issues/641)
=> feat(): add atTopThreshold(#641)

site/docs/getting-started.md
Use the new name for isScrolling in the docs
=> Docs: scrollingStateChange --> isScrolling

e2e/gap.test.ts, examples/gap.tsx, src/List.tsx, src/Table.tsx, src/hooks/useChangedChildSizes.ts, src/initialItemCountSystem.ts, src/listStateSystem.ts, src/listSystem.ts, src/scrollIntoViewSystem.ts, src/scrollToIndexSystem.ts, src/sizeSystem.ts, src/upwardScrollFixSystem.ts, test/sizeSystem.test.ts
Follow-up to #686, adds gap support to regular Virtuoso list as well.
Tried to cover at least as much ground as I did with VirtuosoGrid, but considering that the regular list has lots more features, there might be some other places where gap should also be taken into account. If there are such places, let me know and I'll fix them.
=> feat: add gap support to Virtuoso

src/listStateSystem.ts
=> fix: rangeChanged callback for GroupedVirtuoso

examples/grid-data.tsx, site/docs/hello.md, src/Grid.tsx, src/components.tsx, src/gridSystem.ts, src/interfaces.ts
Resolves #523. Not sure if worth it, the workaround from the issue is rather simple, but as we started implementing our wrapper around VirtuosoGrid, kind of a nuisance that the component API is different from regular Virtuoso.
=> feat: support data in VirtuosoGrid

src/components.tsx
Missed this definition when adding data, got in the way when I started to update.
=> fix: typedef of VirtuosoGrid const

CONTRIBUTING.md, examples/grid-responsive-columns.tsx, src/gridSystem.ts, test/gridSystem.test.ts
=> fix: recalc grid state when viewport dimensions change

src/interfaces.ts
Fix Comment on ScrollSeekConfiguration exit
=> Fix Comment on ScrollSeekConfiguration exit

src/interfaces.ts
Fixes: https://github.com/petyosi/react-virtuoso/issues/932
=> fix: add children to TableHead & TableFoot types

src/TableVirtuoso.tsx, src/Virtuoso.tsx
Fixes https://github.com/petyosi/react-virtuoso/issues/991
=> fix: dont render item into html element

src/gridSystem.ts, test/Grid.test.tsx
Fixes https://github.com/petyosi/react-virtuoso/issues/1161
=> fix: grid does not render items when initialTopMostItemIndex is set to 1 or more

src/topItemCountSystem.ts
Fix for [this](https://github.com/petyosi/react-virtuoso/issues/1163) issue.
=> Fix topItemCountSystem to accept zero value
