petyosi/react-virtuoso

src/Style.tsx

In IE, CSSStyleSheet.insertRule must has `index` argument
https://developer.mozilla.org/ko/docs/Web/API/CSSStyleSheet/insertRule
Without this param, IndexSizeError will be executed

Fix bug with CSSStyleSheet.insertRule in IE

---

src/Virtuoso.tsx

This PR addresses an issue regarding sorting lists. Using raw indexes as keys is discouraged in react and giving consumers the ability to provide custom keys for each row allows for stable reconciliation. Without it issues like incorrectly updated DOM nodes will pop up and cause broken UI.
@petyosi Would be awesome to get this merged. I added this functionality to our local fork but figured it would make sense for everyone who has the use case of lists which are being sorted.

feat: allow custom item keys via `computeItemKey`

---

src/Utils.tsx

Copies the approach used in https://github.com/hshoff/vx/pull/335 to fix a "ResizeObserver loop limit exceeded" error

fix: "ResizeObserver loop limit exceeded"

---

src/Virtuoso.tsx

#22 added `computeItemKey` but marked it as a required property. This PR makes it optional.

Made computeItemKey optional

---

src/Style.tsx
src/Utils.tsx
src/VirtuosoList.tsx
src/VirtuosoView.tsx

This PR is motivated by `VirtuosoStyle` injecting a style tag into the document's head, meaning that it collides with the recommended CSP guidelines, to remove any inlined style tags.
The sticky elements style attributes will now be passed directly to the component, not affecting possibly existing CSP rules.

Remove inline style tag in favour of inline styled components

---

src/engines/scrolledToBottomEngine.ts

I found that variable `notAtBottom` is always undefined but used in `clearTimeout`. I'm not sure whether we should clear the timer or we just need to remove `notAtBottom` with `clearTimeout`

Fix scrolledToBottom timer isn't cleared

---

src/engines/scrollToIndexEngine.ts

Calling scrollToIndex with align="center" and a target index smaller than the range in view was sometimes setting scrollTop to a negative value. If the behavior="smooth" that was making it stop rendering on scroll. So this is a small change to clamp scrollTop to a positive number, which fixes the problem.
I can reproduce this on a list with fixed itemHeight=80 like this:
```
setTimeout(() => {
refVirtualList.current.scrollToIndex({ index: 22, align: 'center', behavior: 'smooth' });
setTimeout(() => {
refVirtualList.current.scrollToIndex({ index: 3, align: 'center', behavior: 'smooth'});
}, 1000)
}, 5000);
```

Fix scrollToIndex going negative

---

src/VirtuosoGrid.tsx
src/VirtuosoGridEngine.ts

This PR adds `initialItemCount` prop to `VirtuosoGrid` and use in `VirtuosoGridEngine` for initializing item range(useful for SSR).

feat(grid-virtuoso): add `initialItemCount` prop

---

src/VirtuosoGrid.tsx
src/VirtuosoGridEngine.ts

This PR contains two improvements:
1. Add `computeItemKey` to the grid props
1.  Replace `transform` and filler component with `padding-top` and `padding-bottom`.
This technique is used in the implementation of virtual scrolling on Instagram. Based on my test changing `transform` will cause layout shifting. Also, the filler component was not necessary because we can update the `padding-bottom` to fill the remaining space(update style of one component instead of two components).

Performance improvement in grid

---

README.md
src/GroupedVirtuoso.tsx
src/Virtuoso.tsx
src/VirtuosoStore.tsx
src/VirtuosoView.tsx
src/engines/listEngine.ts
src/engines/offsetListEngine.ts
test/VirtuosoStore.test.ts

This PR adds a header prop to Virtuoso, GroupedVirtuoso to help show indicators during pagination when using the list from bottom to top.
I'm creating a chat list like slack. and using scrolling from bottom to top and the indicator should be at the top of the list.
I added the header in the same way as the footer.

Add `header` prop

---

src/GroupedVirtuoso.tsx
src/Virtuoso.tsx
src/VirtuosoStore.tsx
src/engines/listEngine.ts

Thank you for merged header prop.
This PR adds a startReached prop to Virtuoso, GroupedVirtuoso to help bottom-up scrolling.
I was implementing it using ScrollContainer but I want to use it like endReached.

Add `startReached` prop

---

playground/followBottom.html
playground/followBottom.tsx
src/engines/scrolledToBottomEngine.ts

This fixes the `scrolledToBottom` calculation so that it also works when window is zoomed in/out. Zooming introduces rounding issues, which this PR fixes. This is related to https://github.com/petyosi/react-virtuoso/issues/184.
Note that the original issue can easily be reproduced by going to https://virtuoso.dev/stick-to-bottom/ and changing the zoom level of the browser. 
This is an alternative fix to https://github.com/petyosi/react-virtuoso/pull/185, which was causing this function to return `true` even when not scrolled to the bottom for me.
I also added the playground files I used to test this change locally. Let me know if they should be removed for this PR to be merged. You can verify locally what this PR does by simply removing the change in `scrolledToBottomEngine.ts`; this …

fix scrolledToBottom calculation

---

site/docs/hello.md

Looks like the property name 'itemCount' was added mistakenly and the information in the doc actually refers to 'itemContent'.

Fix incorrect property name

---

e2e/grid-optimize-rendering.tsx
e2e/grid.tsx
e2e/window-grid.tsx
src/List.tsx
src/hooks/useSize.ts
src/interfaces.ts

This PR introduces a small new feature that allows the definition of a custom component for `TopItemListContainer`, this is useful to set a custom z-index or a different strategy for sticky position.
I had to do the following additional changes due to problems with setup:
Node: v12.18.3
NPM: 6.14.6
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H2
I had to change this
```
const ListContainer: GridComponents['List'] = styled.div`
display: flex;
flex-wrap: wrap;
`
```
to 
```
const ListContainer = styled.div`
display: flex;
flex-wrap: wrap;
` as GridComponents['List']
```
because I was getting that `Types of property 'propTypes' are incompatible.` between `StyledComponent` and `GridProps`
I've also had to change this
```
const observer = new ResizeObserver((entries) => { …
```

feat(): support custom TopItemListComponent

---

src/hooks/useScrollTop.ts

scrollToIndex works with html height:100%

fix(): use document.documentElement.scrollHeight

---

e2e/header-footer.tsx
src/sizeRangeSystem.ts

I have missed an edge case in #417
When header height is greater than item height from visible range is wrongly calculated.

fix: from visible range calculation

---

src/components.tsx

Right now, the typings of this package can throw the following error when `allowSyntheticDefaultImports` is disabled. This can easily be avoided.
```
[error] TypeScript error node_modules/.pnpm/react-virtuoso@1.10.4_react@16.14.0/node_modules/react-virtuoso/dist/components.d.ts:1:8 - error TS1259: Module '"/home/.../node_modules/.pnpm/@types/react@16.14.11/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
import React, { ForwardRefExoticComponent, ReactElement, Ref } from 'react';
```
I believe you don't actually need to default import React here, correct?

Fix type issue arising from React import

---

src/loggerSystem.ts

Hello!
Even after https://github.com/petyosi/react-virtuoso/commit/922a4681f9a34253eb1f61b6137e23fc4576db5d , I still had the same problem reported in https://github.com/petyosi/react-virtuoso/issues/473 in old browsers:
I was able to simulate locally by running `delete globalThis` in the console and going to a screen that uses `react-virtuoso`, then the application crashed, as reported by Sentry. This happens because the browser throws a `ReferenceError` if you try to evaluate a non-defined variable:
Therefore `globalThis || window` threw an error in older browsers.
I tried locally the same scenario with this fix I'm submitting and my application is not breaking anymore with it.

fix: globalThis fallback

---

site/docs/hello.md

[As stated in issue 523](https://github.com/petyosi/react-virtuoso/issues/523#issuecomment-992457927):
> data is not supported for the grid component.

Clarify `data` does not work for VirtuosoGrid

---

src/interfaces.ts

I get an type error when trying to run [MUI Table example](https://virtuoso.dev/mui-table-virtual-scroll/) as a TypeScript project.
<details>
<summary>error message</summary>
```
No overload matches this call.
Overload 1 of 2, '(props: { component: ElementType<any>; } & { children?: ReactNode; classes?: Partial<TableBodyClasses> | undefined; sx?: SxProps<Theme> | undefined; } & CommonProps & Omit<...>): Element', gave the following error.
Property 'component' is missing in type '{ ref: ForwardedRef<HTMLDivElement>; style?: CSSProperties | undefined; children?: ReactNode; 'data-test-id': string; context?: any; }' but required in type '{ component: ElementType<any>; }'.
Overload 2 of 2, '(props: DefaultComponentProps<TableBodyTypeMap<{}, "tbody">>): Element', gave the following error.
Type …
```

fix: fix TableBody type

---

src/List.tsx
src/interfaces.ts

Fixes #635 
Also improved the typing of ItemProps and GroupProps to reflect that they are getting these additional props sent to them (children and style).

refactor: prefer constant for Item.style

---

src/components.tsx

Hello, I was going to create an issue but this should solve it.
---
**Reproduction**
I was using the `initialItemCount` property to SSR some elements, works fine but TS can't find the property on a VirtuosoGrid component!
https://codesandbox.io/s/sandpack-project-forked-67ks79?file=/App.tsx
**To Reproduce**
Steps to reproduce the behavior:
1. Go to https://codesandbox.io/s/sandpack-project-forked-67ks79?file=/App.tsx
2. Scroll down to line 38
4. See error `Property 'initialItemCount' does not exist on type 'IntrinsicAttributes & VirtuosoGridProps<any> & { ref?: Ref<VirtuosoGridHandle>; }'`
**Expected behavior**
The property works but TS does not recognize it
---
I could not test the docs locally but from what I saw in the Readme, and the code, they are created from this file .
Let me know …

Add initialItemCount property to VirtuosoGrid component

---

src/components.tsx

The itemSize TypeScript definition seems wrong. It wants offsetHeight/offsetWidth instead of height/width
Related: #687

Fix TS definition for itemSize prop

---

src/components.tsx

From what I understand from the list behaviour, the attributes accept pixel values. I had initially confused it with the number of items/elements from the top. It would have saved me a lot of time if I knew it was pixels instead.

docs: `atTopThreshold` and `atBottomThreshold` accepts pixel values

---

examples/scroll-into-view-align.tsx
src/interfaces.ts
src/scrollIntoViewSystem.ts

In my use case I want to render a list of files, where the current file should be centered only it if wasn't visible in the tree when it was selected. This didn't seem possible with the existing `scrollIntoView` API (which always scrolled the item to the bottom/top), so I added an `align` property similar to the one used for the `scrollToIndex` function.

feat: support `align` property on `scrollIntoView`

---

src/hooks/useChangedChildSizes.ts

Fix issue https://github.com/petyosi/react-virtuoso/issues/710 for IE11

fix: fix value type and add optional chaining (IE11)

---

src/interfaces.ts

We have customized the Table component in the following way, where we need to add additional children after the virtualized rows:
```
Table: ({ context, ...rest }) => {
const Footer = propComponents?.Footer ?? TableLoadingFooter;
const totalWidth = context?.columns
? getTotalTableMinWidth(context.columns, context?.selectedRows !== undefined)
: undefined;
return (
<table className={styles.table} {...rest} style={{ minWidth: totalWidth, ...rest.style }}>
{rest.children}
{loadMoreData !== undefined && <Footer context={context} />}
</table>
);
},
```
Currently, children is not in the props, which causes issues with React 18 and TypeScript. Seems like children is already picked to most other customizable components, so it seems fine to add it to TableProps as well.

fix: allow children on custom Table component

---

src/Grid.tsx
src/components.tsx

Exposes the context prop on the grid component. I am not sure if we would need anything more on this one

fix: expose context prop for grid

---

package.json
site/docs/mocking-in-tests.md
site/sidebars.js
src/List.tsx
src/Table.tsx
src/index.tsx
src/utils/context.ts
test/VirtuosoMockContext.test.tsx
test/__snapshots__/VirtuosoMockContext.test.tsx.snap
yarn.lock

Initial idea on how this could be implemented.
To use it, one would then have to mock the listState object in tests:
```tsx
<VirtuosoContext.Provider
value={{
listState: {
items: data.map((i, idx) => ({
data: i,
index: idx,
offset: 0,
size: 0,
originalIndex: idx,
})),
},
}}
>
<Virtuoso data={data} />
</VirtuosoContext.Provider>
```
However, this is not quite developer-friendly:
- it expects that you always have the mock data available in tests. In reality, the data can come from elsewhere, e.g. some mocked query result or something like that.
- having to map the data to pass forward all the different internal variables is quite cumbersome.
Ideally, I would only want to tell the context provider how many items I want to render (n or "all"). But the data is not currently available in …

feat: add VirtuosoMockContext for mocking state

---

examples/react-table-flexlayout.tsx
examples/table-markup.tsx
src/Table.tsx
src/components.tsx
src/domIOSystem.ts
src/interfaces.ts
src/scrollToIndexSystem.ts
src/totalListHeightSystem.ts

Closes #570 
This PR adds the `fixedFooterContent` prop to the `TableVirtuoso`. It works almost identically to `fixedHeaderContent`, except it renders a `tfoot` instead of a `thead`.
I wasn't exactly sure if there were tests I needed to add. I mostly mimicked what I saw being done with `fixedHeaderContent`. I'm pretty new to the urx framework, so forgive me if I made mistakes.

feat: add fixed footer content to TableVirtuoso

---

site/docs/mocking-in-tests.md
src/Grid.tsx
src/utils/context.ts
test/VirtuosoMockContext.test.tsx
test/__snapshots__/VirtuosoMockContext.test.tsx.snap

~~Note: this is stacked on top of #766, will rebase once that one gets merged, but you can look at the latest commit in this branch for all the mocking related changes. Could not figure out how to stack PRs from a fork properly~~ 🙃
This adds a separate mock context for VirtuosoGrid, as it needs more data than List/Table.

feat: mock context for grid

---

examples/grid-header-footer.tsx
src/Grid.tsx
src/components.tsx
src/gridSystem.ts
src/interfaces.ts

Closes #197.
We really only need Footer for showing a loading indicator, like in the issue, but as I wanted to use similar props and examples to List, added Header as well (otherwise the `headerFooterTag` prop would be a bit weird...).
Mostly copied over the implementation from List, not sure if the heights need to be added to some calculations manually as well or will the domIoSystem forward everything automatically? The example I added seemed to work okay.

feat: add Header and Footer to VirtuosoGrid

---

src/gridSystem.ts
test/Grid.test.tsx

Another bugfix. The item data was not defined for the probe item. causing errors when the component called `computeItemKey` or `itemContent` fn props that expected data to always be there.
I also duplicated some parts of the existing `List.test.tsx` for Grid to somewhat test this behavior - without the changes, it would also fail.
Sorry about all the bugs :)

fix: probe item data in VirtuosoGrid

---

src/upwardScrollFixSystem.ts

closes #788 
I have run the tests and made sure they pass.

fix: upward scroll after scrollTo glitch in iOS Chrome / Webview

---

src/interfaces.ts

The types for ListRootProps, TableRootProps and GridRootProps were passing the tag name to React.HTMLProps, instead of the HTML element type.

Fix types of props

---

src/TableVirtuoso.tsx

Passes context to FillerRow, which [the props interface says the component should already receive](https://github.com/petyosi/react-virtuoso/blob/master/src/interfaces.ts#L188).
We want to use it to work around https://github.com/petyosi/react-virtuoso/issues/609, as we know the column count via the passed context.

fix: provide context to filler row

---

src/VirtuosoGrid.tsx
src/component-interfaces/TableVirtuoso.ts
src/component-interfaces/VirtuosoGrid.ts

Fixes multiple regressions from 397cf169c0b0447cbee875752694b89f9d235711. 
1. As `VirtuosoGridProps` accepts two generic parameters, so should the component.
2. Also, context prop was removed from `VirtuosoGridProps` the props for some reason, which I added back.
3. Also, `fixedFooterContent` prop on TableVirtuoso seems to have gone missing from the props interface, even though the implementation remained. Added this back as well, we use it.

fix: VirtuosoGrid and TableVirtuoso type definiton

---

examples/auto-prepend-items.tsx
ladle.vite.config.ts
package.json
src/TableVirtuoso.tsx
src/Virtuoso.tsx
src/VirtuosoGrid.tsx
src/hooks/useIsomorphicLayoutEffect.ts
src/hooks/useScrollTop.ts
src/hooks/useSize.ts
src/hooks/useWindowViewportRect.ts
src/interfaces.ts
src/react-urx/index.ts
src/utils/context.ts
vite.config.ts

Relates to https://github.com/petyosi/react-virtuoso/issues/814 and 2103a3354697081af597b43b916eae8bba415271.
The mjs extension specifically is problematic, as some bundlers expect everything from that file down to also be proper ESM. In this lib, the React imports specifically are problematic for webpack, as react is not distributed as ESM, so I get these errors after upgrading:
> ERROR in ./node_modules/react-virtuoso/dist/index.mjs 363:31-44 Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
I'm not sure if changing the extension is the only solution, but it's definitely the easy one, I verified that changing this in node_modules works and requires no major changes on the consumer side (I still have to pass it through …

fix: use default export from react and react-dom, build with classic jsx runtime

---

examples/remove-items.tsx
src/listStateSystem.ts
test/Virtuoso.test.tsx

Fixes #809. Skipping the recalc if totalCount is not in sync with data.length seems to fix the issue, but I'm not entirely sure if there is maybe some better way of ensuring that the updates would be batched?

fix: skip recalc if data changes before totalCount

---

site/docusaurus-sandpack/src/theme/CodeBlock/style.css

The copy button is not displayed well on the current code block background, so fix it.

docs: update the default code copy button color

---

src/gridSystem.ts
test/gridSystem.test.ts

- Fix `itemsPerRow()` calculation to handle edge cases related to element dimension precision
- Add tests with experimentally-determined edge cases that cause precision problems with the
previous calculation
- fixes [BUG] `VirtuosoGrid` + CSS Grid `List` component: items not rendered #889
`react-virtuoso` calculates element dimensions using `getBoundingClientRect()`. This value may be
imprecise when the browser view is zoomed in/out, though technically it is [more precise than eg
`clientWidth`](https://developer.mozilla.org/en-US/docs/Web/API/Element/clientWidth).
To see this for yourself, use `getBoundingClientWidth()` and `clientWidth` to measure the width of
a relatively sized element at various zoom levels. `clientWidth` reports the same value each time,
while …

fix(gridSystem): fix `itemsPerRow` precision

---

src/TableVirtuoso.tsx

I've been using your library recently and stumbled across an issue. When scrolling, the style of TableRow is changing between rerenders, which stops it from being properly memoized.
I traced this back to inline styles changing the referential equality between renders. So, I made a small tweak: I moved the stable style to an outside scope. Now, the TableRow is memoizing like a champ.
I saw something similar being done in the Virtuoso component (https://github.com/petyosi/react-virtuoso/blob/cb156cc3009cc544ca31eb30041ef35c4a278f8d/src/Virtuoso.tsx#L68), so I guess it's in line with your usual patterns.
To help illustrate the impact of this change, I've taken before-and-after snapshots from React's profiler tab (modified example from https://virtuoso.dev/table-fixed-headers/). 
before: …

fix: move stable item style to outside scope

---

src/initialItemCountSystem.ts
test/ssr.test.tsx

Currently, when using `initialItemCount`, it would always render the first `N`
items (starting at 0). With this change, it will still render N items, but start at the offset provided by `initialTopMostItem`.
This PR contains the work performed by @TrueCarry for issue #361 plus some changes based on the feedback provided there. 
There is one issue however: due to the filter for `scrolledToInitialItem`, the rendered items will always have a `visibility: hidden` (unless the offset is 0, thus recreating the old behaviour). This would mean that, while the correct section will be rendered, it will be hidden.
https://github.com/petyosi/react-virtuoso/blob/16b418b8fae443b59ad379850b9b7d2be2c69e61/src/initialTopMostItemIndexSystem.ts#L22-L30
I have added a test case to test this, but I am not …

feat: offset the `initialItemCount` with the `initialTopMostItem`

---

examples/table-state.tsx
src/TableVirtuoso.tsx
src/component-interfaces/TableVirtuoso.ts

I noticed that the table docs mentioned `restoreStateFrom` but this feature is not implemented. This pull request adds that functionality. If there is more to be done I will happily do so. I tested the functionality in `table-state.tsx`.
Also whilst I am working on tables. I would love to update the react-table integration documentation because the package is updated, nowadays it is tanstack table. My question is should I leave the react-table docs as is for backwards compatibility and create a seperate example called tanstack/table or should I replace it alltogether?

feat: added table-state

---

src/Virtuoso.tsx

I just found a small mistake. Context appears as an attribute of the DOM element.

fix: prevent adding context as an attribute of the TopItemList's DOM element

---

src/hooks/useSize.ts

this should fix #1060 
Very ugly and extreme example where it happens: https://codesandbox.io/p/sandbox/red-glitter-hcqz3d?file=%2FApp.js%3A62%2C1 
After fix: https://codesandbox.io/p/sandbox/hungry-roentgen-3ff9yp

fix: stop "Zero-sized element, this should not happen" error from showing up when it should not

---

src/Virtuoso.tsx
src/VirtuosoGrid.tsx
src/interfaces.ts
test/__snapshots__/VirtuosoMockContext.test.tsx.snap

Adjust the way used to set data test `Scroller`, `List`, `GridList`
- Instead of setting `Scroller`, `List`, `GridList` with test id like `data-test-id`, but set them with `data-testid` as its test id
When looked into e2e tests in current main branch, it seems there're adjustments needed, but it could be separately to another PR only for fixing current e2e tests.
If purpose of this PR is focused enough and  seems like a good fix, it'd be cool to see it become part of the library. Thanks for your time, and kudos for your fantastic works in open-source 🙇

fix: adjust the way used to set data test Scroller, List, GridList

---

src/component-interfaces/TableVirtuoso.ts

Hey @petyosi! First of all, thanks for the awesome library!
I've noticed that `initialTopMostItemIndex` in `<TableVirtuoso />` has type `number`, but `IndexLocationWithAlign` is also supported.
[Demo](https://shortlurl.com/6650acc92d00b)

fix: update `initialTopMostItemIndex` type in `TableVirtuoso` interface

---

src/TableVirtuoso.tsx
src/Virtuoso.tsx
src/VirtuosoGrid.tsx

Add `React.useMemo` for `useSize` input param to prevent `callback` param may accidentally updated, which makes unnecessary [ResizeObserver recreation](https://github.com/petyosi/react-virtuoso/blob/master/src/hooks/useSize.ts#L14), to speed up scroll performance.

feat: add memo for useSize argument

---

examples/state.tsx
src/stateLoadSystem.ts

RE: https://github.com/petyosi/react-virtuoso/issues/1081

fix: account for headerHeight when restoring state

---

src/TableVirtuoso.tsx
src/component-interfaces/TableVirtuoso.ts

Resolves #1130 .
I wanted to separate topItems from items as in `Virtuoso.tsx`, but in the case of `TableVirtsuoso.tsx`, the Items component contains a TableBodyComponent, so I could not put a TableRowComponent outside of it, and So, this is how it is implemented.
If you have any ideas for a better implementation, I'd be happy to point them out.

feat: topItemCount for TableVirtuoso

---

apps/virtuoso.dev/docs/guides/table-virtuoso/table-grouped.md
packages/react-virtuoso/src/TableVirtuoso.tsx
packages/react-virtuoso/src/component-interfaces/TableVirtuoso.ts
packages/react-virtuoso/src/interfaces.ts

I'm interested in leveraging the functionality added in #792, but it seems that PR has stalled out.
It appears `topList` support had been added to TableVirtuoso since that PR was active, which did most of the heavy lifting. The issues with height calculations from #792 were most likely due to trying to include the sticky group items in the `thead`, as opposed to `tbody`/`<Items />` as they are here.
Let me know if there's anything I can do to clean this up to prepare it for release, and thanks for your great work on this package! The `react-urx` FRP systems were fun to explore

feat: Adds GroupedTableVirtuoso to support grouping on tables
